//
//  BridgingHeader.h
//  SimpleChain
//
//  Created by Vincenzo Ajello on 13/11/17.
//  Copyright © 2017 Vincenzo Ajello. All rights reserved.
//

// This file is autogenerated by xCode when a obj-c
// file is drag & dropped in the project

#ifndef BridgingHeader_h
#define BridgingHeader_h

#import <CommonCrypto/CommonHMAC.h>

#endif /* BridgingHeader_h */
